[build]
  publish = "public" # This should match your EJS output directory
  command = "node render.ejs.js" # Or your actual build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200